### ISSUE TITLE
OMG IM YOUR BIGGEST FAN

### ISSUE THREAD

**Issue by it4e** [ImFalling/FrickShow#2]
OMG I LOVE YOUR WORK YOU ARE SUCH A GOOD PROGRAMMER OMG OMG OMG! I WANT TO BE  AS GOOD AS YOU WHEN I GROW UP. PLZ TEACH ME NOW!

**Comment by ImFalling** [comment]
under de table, saggy bitch cunt

**Comment by ImFalling** [comment]
Vettefan om det var sarkastiskt eller whatnot, men fuck you, ditt äckel.

**Comment by it4e** [comment]
<33333333333333 8===D ~~~~~

**Comment by it4e** [comment]
fUCKKKK
